### ISSUE TITLE
[suggestion] Auto Updater

### ISSUE THREAD

**Issue by nurdism** [RNG42/NoitaSeedChanger#1]
Thank you for making this tool, it works great, it would be nice to have an Auto Updater for the frequent changes that Noita keeps pushing out.

**Comment by nurdism** [comment]
idea to achieve this would to have a json file with game version and memory addresses that the app could fetch on start up

**Comment by RNG42** [comment]
Thanks for the suggestion. The most optimal would be to be able to get the memory addresses dynamically, without having to put them into a json file manually. But i was looking for a different solution anyways and this would be a viable option for sure.
