### ISSUE TITLE
Memory address of seed is different after Nov 20 2019 update.

### ISSUE THREAD

**Issue by NipunRamani99** [RNG42/NoitaSeedChanger#3]
Hi I tried NSC after Nov 20 update and found that seed was not changing. I checked the seed location in CE and it's at location 0x145059C,0x14DE1E0. I changed the p_Final array with only these two values in Program.cs and it worked. Also had to change the hash string value in Release.cs for final. If anybody is facing the same issue, maybe try to this.

**Comment by RNG42** [comment]
Fixed and released the Update.
