### ISSUE TITLE
No NoitaSeedChanger.exe

### ISSUE THREAD

**Issue by DiggiiLife** [RNG42/NoitaSeedChanger#5]
Hello i am wondering where the NoitaSeedChanger.exe is, and i really want to try this seed changer and the instructions say there is a NoitaSeedChanger.exe but there is no such file i don't know why there is no file, i hope you can fix something or tell me if im missing something. thanks

**Comment by RNG42** [comment]
You have probably downloaded the source code. Download 'NSC.zip' from the release page, right here:
https://github.com/RNG42/NoitaSeedChanger/releases
